_wandb:
    value:
        cli_version: 0.25.1
        e:
            xtl4zg8v0qlqchrls3yhqv2gnydyi6v4:
                args:
                    - --storage-path
                    - ./evolve_storage
                    - examples/evolve_config.yml
                    - --vllm
                    - --force-population-size
                    - "4"
                    - --wandb
                    - --wandb-project
                    - merge_4b
                    - --wandb-entity
                    - yamalies-ajio
                    - --task-search-path
                    - tasks
                    - --i-understand-the-depths-of-the-evils-i-am-unleashing
                codePath: .venv/bin/mergekit-evolve
                codePathLocal: .venv/bin/mergekit-evolve
                cpu_count: 30
                cpu_count_logical: 30
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "532608356352"
                        used: "143212077056"
                email: yamalchrischan@gmail.com
                executable: /teamspace/studios/this_studio/mergekit/.venv/bin/python3
                git:
                    commit: 561e8b1808d8fcdf20cd92678079cd2a6c9973c2
                    remote: https://github.com/wilfrid51/mergekit.git
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-37b7fa95-faeb-88b9-7d35-a1cf5f7e7e28
                host: 150-136-215-229
                memory:
                    total: "232205713408"
                os: Linux-6.8.0-60-generic-x86_64-with-glibc2.39
                program: /teamspace/studios/this_studio/mergekit/.venv/bin/mergekit-evolve
                python: CPython 3.12.11
                root: /teamspace/studios/this_studio/mergekit
                startedAt: "2026-03-26T08:12:58.619700Z"
                writerId: xtl4zg8v0qlqchrls3yhqv2gnydyi6v4
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 5
                - 11
                - 30
                - 41
                - 49
                - 51
                - 53
                - 71
                - 95
                - 98
            "2":
                - 1
                - 5
                - 11
                - 30
                - 41
                - 49
                - 51
                - 53
                - 71
                - 95
                - 98
            "3":
                - 16
                - 41
            "4": 3.12.11
            "5": 0.25.1
            "6": 5.3.0
            "12": 0.25.1
            "13": linux-x86_64
apply_chat_template:
    value: true
fewshot_as_multiturn:
    value: true
genome:
    value:
        allow_negative_weights: false
        base_model: Qwen/Qwen3-4B
        filters:
            - mlp
            - self_attn
        layer_granularity: 6
        merge_method: ties
        models:
            - jeff4000/4b_1
            - jeff4000/4b_2
        normalize: true
        smooth: false
        tokenizer_source: null
limit:
    value: 10
num_fewshot:
    value: 0
random_init:
    value: false
shuffle:
    value: false
tasks:
    value:
        - metric: accuracy,none
          name: cryptarithm
          weight: 1
        - metric: accuracy,none
          name: trace
          weight: 1
