genome:
  models:
    # - EdmondMillion/affine-28-5CSriXZUwkoqdKBF4kqgRPBgrRiyPbLEo6TBaR3rW3u5qo4T
    # - vera6/affine-5GEY63hvpsKAELBtz64a5Xa7cdsEUdLqMK3JEdxfoQ1i1GqK
    - jeff4000/4b_1
    - jeff4000/4b_2
  merge_method: ties
  # base_model: Qwen/Qwen3-32B
  base_model: Qwen/Qwen3-4B
  layer_granularity: 6
  normalize: true
  filters:
    - mlp
    - self_attn


tasks:
  # - name: webqs
  #   weight: 1.0
  # - name: humaneval
  #   weight: 1.0
      # metric: "pass@1,none"
  # - name: truthfulqa
  #   wiehgt: 1.0
  # - name: asdiv
  #   weight: 1.0
  # - name: coqa
  #   weight: 1.0
  #   metric: "em,none"
  # - name: coqa
  #   weight: 1.0
  #   metric: "f1,none"
  # - name: fda
  #   weight: 1.0
  #   metric: "contains,none"
  - name: drop
    weight: 10.0

num_fewshot: 0
apply_chat_template: true
fewshot_as_multiturn: true
confirm_run_unsafe_code: true