genome:
  models:
    - jeff4000/4b_1
    - jeff4000/4b_2
    # - affshoot/Affine-II_5FLiMuk4H8vKRQ19vs3phPdpdkCtqAeaWVRqufgUXxvM4QzQ
    # - anton-ro/affine-5DZTN94ofug3s2oPN7ehuKFGekQkGVRGWnmsPRqab1tVDABc
    # - jeff4000/4b_4
  merge_method: ties
  # base_model: Qwen/Qwen3-32B
  base_model: Qwen/Qwen3-4B
  layer_granularity: 6
  normalize: true
  filters:
    - mlp
    - self_attn


tasks:
  # - name: hellaswag
  #   weight: 1.0
  # - name: winogrande
  #   weight: 1.0
  - name: cryptarithm
    weight: 1.0
    metric: accuracy,none
  - name: trace
    weight: 1.0
    metric: accuracy,none

limit: 4
num_fewshot: 0
apply_chat_template: true
fewshot_as_multiturn: true